# Generated by Django 2.0.7 on 2018-09-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
    ]
