# Generated by Django 2.0.7 on 2018-09-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
