# Generated by Django 2.0.7 on 2018-09-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_reviews_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
